### ISSUE TITLE
Stuck at downloads

### ISSUE THREAD

**Issue by hedonnn** [small-cactus/M.I.L.E.S#32]
On Windows 11, I'm stuck there: 

`PS C:\Miles-env\M.I.L.E.S\Miles-V2> npm start

> m.i.l.e.s@2.0.0 start
> electron .

Server started on http://localhost:3000
API keys are empty, initializing setup screen...
Python Output: [Miles is Downloading wake word model...]

Python Output: [Miles is Wake word models downloaded...]

Python Output: [Miles is Downloading speech recognition models...]

Python Output: [Miles is Base model downloaded successfully...]

Python Output: [Miles is Downloading tiny model...]

Python Output: [Miles is Tiny model downloaded successfully...]

Python Output: [Miles is Ready for speech, try saying 'this is a test']

Python Output: Switching to tiny model due to: Transcription took longer than 3 seconds with the base model.

Config Python Error: Traceback (most recent call last):
  File "C:\Miles-env\M.I.L.E.S\Miles-V2\config.py", line 70, in <module>

Config Python Error:     print(f"[Miles is You said: {text}]")

Config Python Error:   File "C:\Python311\Lib\encodings\cp1252.py", line 19, in encode

Config Python Error:     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^
Config Python Error: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 21-27: character maps to <undefined>

Config script exited with code 1`

**Comment by hedonnn** [comment]
Oh well I couldn't have guessed that, I don't have a Spotify account and don't intend to use any...

**Comment by small-cactus** [comment]
You don't need a premium account, just a free developer account.

To use the Spotify features you need a premium account, but the app will work without one as long as the API keys are set to something that isn't empty.

You can open the apikeys.py file and replace empty with any random characters for the Spotify values and the app will run without them. If you ask miles to play a song the app will probably crash though.

**Comment by hedonnn** [comment]
OK now I don't find any apikeys.py file anywhere unfortunately...

**Comment by hedonnn** [comment]
It's stuck at "Listening for Miles"

My mic is working, I say "Miles" "hey miles" "hi miles", nothing happens..

`PS C:\Miles-env\M.I.L.E.S\Miles-V2> npm start

> m.i.l.e.s@2.0.0 start
> electron .


Server started on http://localhost:3000
API keys are set, starting server and backend...
Server is already running on port 3000
Python Error: C:\Miles-env\M.I.L.E.S\Miles-V2\main.py:1: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
  from cgi import print_directory

Python Output: Tool list JSON has been saved to C:\Miles-env\M.I.L.E.S\Miles-V2\plugin_tool_list.json

Python Output: Listening for 'Miles'...
`

**Comment by small-cactus** [comment]
Adjust the threshold in main.py,They are located at Line 1071 and line 1084. Adjust the correct one for your platform.

**Comment by hedonnn** [comment]
OK I set it up at 0.0001 and I went pass by "Listening to Miles" it's now stuck at "Listening for prompt" it doesn't seems to listen at all, nothing happens when I talk to it.

**Comment by small-cactus** [comment]
You either have a very loud room, a noisy mic, or the mic isn't working for Miles at all

**Comment by hedonnn** [comment]
I don't think it would pass the "listening for "Miles" if it wasn't working.
My room is very very very quiet. Maybe the software doesn't recognize my mic anymore past the first "Listening for Miles"?

**Comment by small-cactus** [comment]
My wake word detection doesn't use transcribed words to hear you, it uses a neural network to predict when you say the word, so it might go off, and then the actual transcription might not be able to hear you if there's too much background noise, it'll never stop listening because it thinks you're still talking
